services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_16_app
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    environment:
      # Эти переменные будут подтянуты из вашего .env файла
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_TO=${EMAIL_TO}
