services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_16_app
    expose:
      - "3000"
    restart: always
    env_file:
      - .env
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_TO=${EMAIL_TO}
      - SECRET=${SECRET}
      - DATABASE_PATH=${DATABASE_PATH}
    volumes:
      - ./entities/bd:/app/entities/bd
    networks:
      - app-network

  nginx-proxy:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./nginx_data:/data
      - ./nginx_letsencrypt:/etc/letsencrypt
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
