services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_16_app
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    environment:
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_TO=${EMAIL_TO}
      - SECRET=${SECRET}
    volumes:
      - ./entities/bd:/app/entities/bd
